baseURL = "https://rafaliserhajaya.com"
disableLanguages = ["fr"]
paginate = "9"
summaryLength = 10
theme = "educenter-hugo"
title = "Rafalis Erha Jaya"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2024 All Right Reserved [Rafalis Erha Jaya](/)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1

[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "product"
name = "product"
weight = 2

[[menu.main]]
URL = "blog"
name = "blog"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5

[[menu.footer]]
URL = "sertifikasi"
name = "sertifikasi"
weight = 1
[[menu.footer]]
URL = "spesifikasi"
name = "spesifikasi"
weight = 2
[[menu.footer]]
URL = "services"
name = "services"
weight = 3
[[menu.footer]]
URL = "project"
name = "project"
weight = 4

[params]
address = "PURI HESTI INSANI RT. 17 RW. 15 No. 3 Desa Mampir Kec. Cileungsi Kab. bogor Jawa Barat Indonesia"
author = "angga cipiet"
contact_form_action = "https://formspree.io/f/movjwyrk"
description = "PT Rafalis Erha Jaya - Produsen beton precast berkualitas tinggi di Cileungsi, Bogor. Spesialis Box Culvert, U-Ditch, dan Fence Panel dengan standar SNI. Melayani area Jabodetabek dan sekitarnya. Solusi drainase terpercaya dengan harga pabrik."
email = "rhprecast@rafaliserhajaya.com"
logo = "images/rafalis.png"
mobile = "081294212524"
top_header = false

[params.map]
#enable = false
#gmap_api = "https://www.google.com/maps?z=16&q=jl.%2Bmanisi%2B(bunderan%2Bcibiru)%2Bcipadung%2Bcibiru%2Bbandung%2B40614"
#map_latitude = "107.00659177478612"
#map_longitude = "-6.4326057629037"
#map_marker = "images/marker.png"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'

[build.buildStats]
enable = true

[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'

[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'

[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = [
  "HTML",
  "RSS",
  "SITEMAP",
  "JSON"
]

[outputFormats]
[outputFormats.Sitemap]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel = "sitemap"

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isHTML = false
isPlainText = true
noUgly = true

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 85
resampleFilter = "lanczos"

[imaging.exif]
disableDate = true
disableLatLong = true
excludeFields = ''
includeFields = ''

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################ Minify #############################
[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
      keepEndTags = true
      keepQuotes = true

############################# Plugins #############################
[params.plugins]
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

[params.preloader]
enable = false
preloader = "images/preloader.gif"

[params.subscription]
enable = true
mailchimp_form_action = "https://rafaliserhajaya.us19.list-manage.com/subscribe/post?u=b254bade3600ade2f1eb9fed1&id=bf4f2bdb2b&f_id=007f88e4f0"
mailchimp_form_name = "b254bade3600ade2f1eb9fed1"


# cookies
[params.cookies]
enable = true
expire_days = 2


[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"

[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

[params.google]
  analytics_id = "G-2PHP592VWS"

[params.algolia]
  enable = true
  app_id = "EE2ODVIPS2"
  search_api_key = "6bafd5632a313d7fa315ae25bd313054"
  index_name = "rafaliserhajaya"

[params.image]
  [params.image.widths]
    default = [400, 600, 800, 1200]