baseURL = "https://rafaliserhajaya.com"
defaultContentLanguage = "id"
paginate = "9"
summaryLength = 10
theme = "educenter-hugo"
title = "Jual U-Ditch & Box Culvert Precast Harga Pabrik - PT Rafalis Erha Jaya, Bogor"

[Languages.id]
contentDir = "content/english"
copyright = "Copyright &copy; 2024 All Right Reserved [Rafalis Erha Jaya](/)"
home = "Beranda"
languageCode = "id"
languageName = "Indonesia"
weight = 1

[[Languages.id.menu.main]]
URL = "about"
name = "Tentang"
weight = 1

[[Languages.id.menu.main]]
URL = "product"
name = "Produk"
weight = 2

[[Languages.id.menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[Languages.id.menu.main]]
URL = "contact"
name = "Kontak"
weight = 5

[[Languages.id.menu.footer]]
URL = "sertifikasi"
name = "Sertifikasi"
weight = 1
[[Languages.id.menu.footer]]
URL = "spesifikasi"
name = "Spesifikasi"
weight = 2
[[Languages.id.menu.footer]]
URL = "services"
name = "Layanan"
weight = 3
[[Languages.id.menu.footer]]
URL = "project"
name = "Proyek"
weight = 4

[params]
address = "PURI HESTI INSANI RT. 17 RW. 15 No. 3 Desa Mampir Kec. Cileungsi Kab. bogor Jawa Barat Indonesia"
author = "angga cipiet"
contact_form_action = "https://formspree.io/f/movjwyrk"
description = "Jual U-Ditch & Box Culvert Precast harga pabrik di Bogor & Cileungsi. PT Rafalis Erha Jaya, produsen beton precast berkualitas SNI untuk proyek drainase & konstruksi Jabodetabek."
keywords = [
  "u-ditch precast bogor",
  "box culvert cileungsi",
  "beton precast bogor",
  "harga u-ditch precast",
  "produsen beton precast bogor",
  "harga box culvert cileungsi",
  "jual beton precast murah",
  "supplier u-ditch bogor",
  "fence panel cileungsi",
  "harga beton precast cileungsi",
  "produsen beton precast cileungsi",
  "harga beton precast bogor",
  "beton precast murah",
  "solusi drainase bogor",
  "jual u-ditch precast cileungsi"
] 
email = "rhprecast@rafaliserhajaya.com"
logo = "images/rafalis.png"
mobile = "081294212524"
top_header = false

[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyB2Nc8a3Qg4IG__s_TOrDU0m1M8ka2-njI"
office_latitude = "-6.4326057629037"
office_longitude = "107.00659177478612"
factory_latitude = "-6.435000"
factory_longitude = "107.010000"
map_marker = "images/marker.png"

[params.office]
title = "Kantor"
address = "PURI HESTI INSANI RT. 17 RW. 15 No. 3 Desa Mampir Kec. Cileungsi Kab. Bogor Jawa Barat Indonesia"

[params.factory]
title = "Pabrik"
address = "Kp. Binong RT.03 RW. 05 No.3 Desa Situsari Kec. Cileungsi Kab Bogor, Jawa Barat - Indonesia"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'

[build.buildStats]
enable = true

[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'

[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'

[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = [
  "HTML",
  "RSS",
  "SITEMAP",
  "JSON"
]

[outputFormats]
[outputFormats.Sitemap]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel = "sitemap"

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isHTML = false
isPlainText = true
noUgly = true

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 85
resampleFilter = "lanczos"

[imaging.exif]
disableDate = true
disableLatLong = true
excludeFields = ''
includeFields = ''

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################ Minify #############################
[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
      keepEndTags = true
      keepQuotes = true

############################# Plugins #############################
[params.plugins]
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"

[params.preloader]
enable = false
preloader = "images/preloader.gif"

[params.subscription]
enable = true
mailchimp_form_action = "https://rafaliserhajaya.us19.list-manage.com/subscribe/post?u=b254bade3600ade2f1eb9fed1&id=bf4f2bdb2b&f_id=007f88e4f0"
mailchimp_form_name = "b254bade3600ade2f1eb9fed1"


# cookies
[params.cookies]
enable = true
expire_days = 2


[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"

[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

[params.google]
  analytics_id = "G-2PHP592VWS"

[params.algolia]
  enable = true
  app_id = "EE2ODVIPS2"
  search_api_key = "6bafd5632a313d7fa315ae25bd313054"
  index_name = "rafaliserhajaya"

[params.image]
  [params.image.widths]
    default = [400, 600, 800, 1200]