[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*.jpg"
  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"