[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "https://rafaliserhajaya.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Content-Security-Policy = """
      default-src 'self' https://*.tinajs.io https://*.github.com https://app.tina.io https://*.amazonaws.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com https://*.tinajs.io;
      style-src 'self' 'unsafe-inline' fonts.googleapis.com;
      img-src 'self' data: www.google-analytics.com https://assets.tina.io https://content.tina.io https://*.tinajs.io blob:;
      media-src 'self' https: blob:;
      connect-src 'self' 
        https://*.tinajs.io 
        https://identity.tinajs.io 
        https://content.tina.io 
        https://assets.tina.io
        https://api.github.com
        https://app.tina.io
        www.google-analytics.com 
        https://*.amazonaws.com 
        https://cognito-idp.us-east-1.amazonaws.com
        https://cognito-identity.us-east-1.amazonaws.com;
      frame-src 'self' 
        https://www.google.com 
        https://identity.tinajs.io 
        https://app.tina.io
        https://www.youtube.com 
        https://youtube.com
        https://player.vimeo.com
        https://*.vimeo.com;
      worker-src 'self' blob:;
      font-src 'self' data: fonts.gstatic.com https://*.tinajs.io https://app.tina.io;
      form-action 'self' https://identity.tinajs.io https://app.tina.io;
    """

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/admin/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/webp"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self' https://*.tinajs.io https://*.github.com https://app.tina.io https://*.amazonaws.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        www.google-analytics.com 
        https://*.tinajs.io  
        https://www.googletagmanager.com 
        https://cdnjs.cloudflare.com
        https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' 
        fonts.googleapis.com
        https://cdnjs.cloudflare.com;
      img-src 'self' data: 
        www.google-analytics.com 
        https://assets.tina.io 
        https://content.tina.io 
        https://*.tinajs.io
        https://www.googletagmanager.com;
      font-src 'self' data: 
        fonts.gstatic.com
        https://cdnjs.cloudflare.com;
      connect-src 'self' 
        https://*.tinajs.io 
        https://identity.tinajs.io 
        https://content.tina.io 
        https://assets.tina.io
        https://api.github.com
        https://app.tina.io
        www.google-analytics.com 
        https://*.amazonaws.com 
        https://cognito-idp.us-east-1.amazonaws.com
        https://cognito-identity.us-east-1.amazonaws.com
        https://www.google-analytics.com
        https://stats.g.doubleclick.net;
      frame-src 'self' 
        https://www.google.com 
        https://identity.tinajs.io 
        https://app.tina.io
        https://www.youtube.com 
        https://youtube.com
        https://player.vimeo.com
        https://*.vimeo.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://identity.tinajs.io https://app.tina.io;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"