[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/assets/*"
  to = "/admin/assets/:splat"
  status = 200

# Admin area security headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Content-Security-Policy = """
      default-src 'self' https://*.tinajs.io https://*.github.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.tinajs.io;
      style-src 'self' 'unsafe-inline' fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      media-src 'self' https: blob:;
      connect-src 'self' 
        https://*.tinajs.io 
        https://identity.tinajs.io 
        https://content.tinajs.io 
        https://api.github.com 
        https://raw.githubusercontent.com 
        wss://*.tinajs.io;
      frame-ancestors 'none';
      form-action 'self';
      worker-src 'self' blob:;
      font-src 'self' data: fonts.gstatic.com;
    """

# Main website security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = """
      accelerometer=(),
      camera=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      payment=(),
      usb=()
    """
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        www.google-analytics.com 
        www.googletagmanager.com 
        www.google.com 
        www.gstatic.com;
      style-src 'self' 'unsafe-inline' 
        fonts.googleapis.com;
      img-src 'self' data: 
        www.google-analytics.com 
        *.google.com 
        *.googleapis.com;
      font-src 'self' 
        fonts.gstatic.com;
      connect-src 'self' 
        www.google-analytics.com 
        analytics.google.com;
      frame-src 'self' 
        www.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache control headers
[[headers]]
  for = "/admin/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{jpg,png,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"